# Generated by Django 3.2 on 2021-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('reasturantName', models.CharField(max_length=30)),
                ('dishName', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
