# Generated by Django 3.2 on 2021-04-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
